# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d8ada8b5240a943a69bf5b60cf195dfa0e40a245fd8d8fb59c107fac2802bd9f2448832eac3de0a63cf1f7ff71106e07bb60563a8a8c95d016072bd6ab0e458

test:
  secret_key_base: 68570b476e1e6c36a4411bcb6afbbeb070870cfb157eebb8660833602e03ce111a75f1be44ed13b375b613ce0a1a54784f937212a5cca2d5f1c60f553b502c4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
